// AUTOGENERATED - DO NOT MODIFY
import ProductListView from '../src/views/ProductListView';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-02-14 20:40:00.526044 +0100 CET m=+0.059735201';

export { 
  ProductListView	
 };

export default {
  "connect_permissions": null,
  "icon": "./icon.png",
  "id": "com.example.stripeworker-csv",
  "name": "Product CSV Import-Export",
  "permissions": [
    {
      "permission": "product_read",
      "purpose": "Export products to CSV"
    },
    {
      "permission": "product_write",
      "purpose": "Import products from CSV"
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://github.com/your-org/stripeworker#readme"
  },
  "stripe_api_access_type": "platform",
  "ui_extension": {
    "views": [
      {
        "component": "ProductListView",
        "viewport": "stripe.dashboard.product.list"
      }
    ]
  },
  "version": "0.0.1"
};
