// AUTOGENERATED - DO NOT MODIFY
import ProductListView from '../src/views/ProductListView';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-02-15 11:35:09.911246 +0100 CET m=+0.068524501';

export { 
  ProductListView	
 };

export default {
  "connect_permissions": null,
  "icon": "./src/icon.svg",
  "id": "com.example.stripeworker-csv",
  "name": "Stripeworker",
  "permissions": [
    {
      "permission": "product_read",
      "purpose": "Export products to CSV"
    },
    {
      "permission": "product_write",
      "purpose": "Import products from CSV"
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://github.com/your-org/stripeworker#readme"
  },
  "stripe_api_access_type": "platform",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "http://localhost:8787/"
      ],
      "image-src": null,
      "purpose": "Connect to local development backend for CSV import/export operations"
    },
    "views": [
      {
        "component": "ProductListView",
        "viewport": "stripe.dashboard.product.list"
      }
    ]
  },
  "version": "0.0.1"
};
