// AUTOGENERATED - DO NOT MODIFY
import ProductListView from '../src/views/ProductListView';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-02-15 16:05:34.2310028 +0100 CET m=+5.020100101';

export { 
  ProductListView	
 };

export default {
  "connect_permissions": null,
  "distribution_type": "private",
  "icon": "./src/icon.png",
  "id": "stripeworker.com",
  "name": "Stripeworker",
  "permissions": [
    {
      "permission": "product_read",
      "purpose": "Export products to CSV"
    },
    {
      "permission": "product_write",
      "purpose": "Import products from CSV"
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://stripeworker.com"
  },
  "stripe_api_access_type": "platform",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://api.stripeworker.com/health",
        "https://api.stripeworker.com/export/start",
        "https://api.stripeworker.com/export/",
        "https://api.stripeworker.com/import/from-stripe-file",
        "https://api.stripeworker.com/import/from-csv-content",
        "https://api.stripeworker.com/import/upload-url",
        "https://api.stripeworker.com/import/",
        "https://api.stripeworker.com/jobs",
        "https://api.stripeworker.com/jobs/",
        "https://api.stripeworker.com/mappings",
        "https://api.stripeworker.com/mappings/",
        "https://api.stripeworker.com/storage/upload",
        "https://api.stripeworker.com/storage/download"
      ],
      "image-src": null,
      "purpose": "Connect to backend API for CSV import/export operations"
    },
    "views": [
      {
        "component": "ProductListView",
        "viewport": "stripe.dashboard.product.list"
      }
    ]
  },
  "version": "1.0.2"
};
